include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - camel_case_types
    
analyzer:
  errors:
    todo: ignore
  
  strong-mode:
    
    implicit-casts: false
    implicit-dynamic: false
    
